<?xml version='1.1' encoding='UTF-8'?>
<flow-build plugin="workflow-job@1436.vfa_244484591f">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <jenkins.branch.BranchIndexingCause plugin="branch-api@2.1206.vd9f35001c95c"/>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.21-458.vcf496cb_839e4">
      <queuingDurationMillis>5466</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>0</buildableDurationMillis>
      <waitingDurationMillis>5464</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
    <jenkins.scm.api.SCMRevisionAction plugin="scm-api@696.v778d637b_a_762">
      <sourceId>380b8771-6cf3-4455-9a22-364af94895c0</sourceId>
      <revision class="jenkins.plugins.git.GitBranchSCMRevision" plugin="git@5.5.2">
        <head class="jenkins.plugins.git.GitBranchSCMHead">
          <name>main</name>
        </head>
        <hash>ba38969c340e4e5bae4bead5504d6bdb1f803a3b</hash>
      </revision>
    </jenkins.scm.api.SCMRevisionAction>
    <org.jenkinsci.plugins.workflow.libs.LibrariesAction plugin="pipeline-groovy-lib@749.v70084559234a_">
      <libraries/>
    </org.jenkinsci.plugins.workflow.libs.LibrariesAction>
    <org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction plugin="pipeline-model-definition@2.2218.v56d0cda_37c72">
      <stagesUUID>d6237dc3-3f84-4254-a851-d29574d8861e</stagesUUID>
      <pipelineDefs>
        <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef plugin="pipeline-model-api@2.2218.v56d0cda_37c72">
          <stages>
            <stages>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Install Docker if Needed</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <name>sh</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>script</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">
                if ! command -v docker &amp;&gt; /dev/null; then
                    echo &quot;Docker is not installed. Installing now...&quot;

                    # Fix ROS key expiration issue
                    sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key                         -o /usr/share/keyrings/ros-archive-keyring.gpg

                    sudo apt-get update
                    sudo apt-get install -y docker.io
                    sudo service docker start
                    echo &quot;Docker is installed successfully!&quot;
                fi
                </value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Build ROS2 Docker Image</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <name>sh</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>script</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">
                cd ~/ros2_ws/src/ros2_ci
                sudo docker build -t fastbot-ros2-test .
                </value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
                <name>Run ROS2 Test in Container</name>
                <branches>
                  <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                    <name>default</name>
                    <steps>
                      <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                        <name>sh</name>
                        <args class="org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTNamedArgumentList">
                          <arguments class="linked-hash-map">
                            <entry>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                                <key>script</key>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTKey>
                              <org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                                <value class="string">
                sudo docker run --rm                     --env=&quot;DISPLAY=$DISPLAY&quot;                     --env=&quot;QT_X11_NO_MITSHM=1&quot;                     --volume=&quot;/tmp/.X11-unix:/tmp/.X11-unix:rw&quot;                     fastbot-ros2-test:latest                     bash -c &quot;source /colcon_ws/install/setup.bash &amp;&amp; ros2 launch fastbot_gazebo test_fastbot_waypoints.launch.py&quot;
                </value>
                              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTValue_-ConstantValue>
                            </entry>
                          </arguments>
                        </args>
                      </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStep>
                    </steps>
                  </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTBranch>
                </branches>
              </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTStage>
            </stages>
            <uuid>d6237dc3-3f84-4254-a851-d29574d8861e</uuid>
          </stages>
          <agent>
            <agentType>
              <key>any</key>
            </agentType>
          </agent>
        </org.jenkinsci.plugins.pipeline.modeldefinition.ast.ModelASTPipelineDef>
      </pipelineDefs>
    </org.jenkinsci.plugins.pipeline.modeldefinition.actions.ExecutionModelAction>
    <hudson.plugins.git.util.BuildData plugin="git@5.5.2">
      <buildsByBranchName>
        <entry>
          <string>main</string>
          <hudson.plugins.git.util.Build>
            <marked plugin="git-client@6.0.0">
              <sha1>ba38969c340e4e5bae4bead5504d6bdb1f803a3b</sha1>
              <branches class="singleton-set">
                <hudson.plugins.git.Branch>
                  <sha1 reference="../../../sha1"/>
                  <name>main</name>
                </hudson.plugins.git.Branch>
              </branches>
            </marked>
            <revision reference="../marked"/>
            <hudsonBuildNumber>4</hudsonBuildNumber>
          </hudson.plugins.git.util.Build>
        </entry>
      </buildsByBranchName>
      <lastBuild reference="../buildsByBranchName/entry/hudson.plugins.git.util.Build"/>
      <remoteUrls>
        <string>https://github.com/kuralme/ros2_ci.git</string>
      </remoteUrls>
    </hudson.plugins.git.util.BuildData>
    <org.jenkinsci.plugins.workflow.steps.scm.MultiSCMRevisionState plugin="workflow-scm-step@427.v4ca_6512e7df1">
      <revisionStates>
        <entry>
          <string>git https://github.com/kuralme/ros2_ci.git</string>
          <hudson.scm.SCMRevisionState_-None/>
        </entry>
      </revisionStates>
    </org.jenkinsci.plugins.workflow.steps.scm.MultiSCMRevisionState>
    <jenkins.metrics.impl.SubTaskTimeInQueueAction plugin="metrics@4.2.21-458.vcf496cb_839e4">
      <queuingDurationMillis>6</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>6</buildableDurationMillis>
      <waitingDurationMillis>0</waitingDurationMillis>
      <executingDurationMillis>3281</executingDurationMillis>
      <workUnitCount>1</workUnitCount>
    </jenkins.metrics.impl.SubTaskTimeInQueueAction>
  </actions>
  <queueId>39</queueId>
  <timestamp>1754725020531</timestamp>
  <startTime>1754725020538</startTime>
  <result>FAILURE</result>
  <duration>3813</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <execution class="org.jenkinsci.plugins.workflow.cps.CpsFlowExecution">
    <result>FAILURE</result>
    <script>pipeline {
    agent any

    stages {
        stage(&apos;Install Docker if Needed&apos;) {
            steps {
                sh &apos;&apos;&apos;
                if ! command -v docker &amp;&gt; /dev/null; then
                    echo &quot;Docker is not installed. Installing now...&quot;

                    # Fix ROS key expiration issue
                    sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
                        -o /usr/share/keyrings/ros-archive-keyring.gpg

                    sudo apt-get update
                    sudo apt-get install -y docker.io
                    sudo service docker start
                    echo &quot;Docker is installed successfully!&quot;
                fi
                &apos;&apos;&apos;
            }
        }

        stage(&apos;Build ROS2 Docker Image&apos;) {
            steps {
                sh &apos;&apos;&apos;
                cd ~/ros2_ws/src/ros2_ci
                sudo docker build -t fastbot-ros2-test .
                &apos;&apos;&apos;
            }
        }

        stage(&apos;Run ROS2 Test in Container&apos;) {
            steps {
                sh &apos;&apos;&apos;
                sudo docker run --rm \
                    --env=&quot;DISPLAY=$DISPLAY&quot; \
                    --env=&quot;QT_X11_NO_MITSHM=1&quot; \
                    --volume=&quot;/tmp/.X11-unix:/tmp/.X11-unix:rw&quot; \
                    fastbot-ros2-test:latest \
                    bash -c &quot;source /colcon_ws/install/setup.bash &amp;&amp; ros2 launch fastbot_gazebo test_fastbot_waypoints.launch.py&quot;
                &apos;&apos;&apos;
            }
        }
    }
}
</script>
    <loadedScripts class="linked-hash-map"/>
    <durabilityHint>MAX_SURVIVABILITY</durabilityHint>
    <timings class="map">
      <entry>
        <string>flowNode</string>
        <long>414445022</long>
      </entry>
      <entry>
        <string>classLoad</string>
        <long>110967705</long>
      </entry>
      <entry>
        <string>runQueue</string>
        <long>1182400095</long>
      </entry>
      <entry>
        <string>run</string>
        <long>1021794810</long>
      </entry>
      <entry>
        <string>parse</string>
        <long>19276821</long>
      </entry>
      <entry>
        <string>saveProgram</string>
        <long>276055513</long>
      </entry>
    </timings>
    <internalCalls class="sorted-set">
      <string>org.jenkinsci.plugins.pipeline.StageStatus.TAG_NAME</string>
    </internalCalls>
    <sandbox>true</sandbox>
    <iota>31</iota>
    <head>1:31</head>
    <done>true</done>
    <resumeBlocked>false</resumeBlocked>
    <storageDir>workflow-completed</storageDir>
  </execution>
  <completed>true</completed>
  <checkouts class="hudson.util.PersistedList">
    <org.jenkinsci.plugins.workflow.job.WorkflowRun_-SCMCheckout>
      <scm class="hudson.plugins.git.GitSCM" plugin="git@5.5.2">
        <configVersion>2</configVersion>
        <userRemoteConfigs>
          <hudson.plugins.git.UserRemoteConfig>
            <name>origin</name>
            <refspec>+refs/heads/*:refs/remotes/origin/*</refspec>
            <url>https://github.com/kuralme/ros2_ci.git</url>
          </hudson.plugins.git.UserRemoteConfig>
        </userRemoteConfigs>
        <branches class="singleton-list">
          <hudson.plugins.git.BranchSpec>
            <name>main</name>
          </hudson.plugins.git.BranchSpec>
        </branches>
        <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
        <submoduleCfg class="empty-list"/>
        <extensions>
          <jenkins.plugins.git.GitSCMSourceDefaults>
            <includeTags>false</includeTags>
          </jenkins.plugins.git.GitSCMSourceDefaults>
          <hudson.plugins.git.extensions.impl.BuildChooserSetting>
            <buildChooser class="jenkins.plugins.git.AbstractGitSCMSource$SpecificRevisionBuildChooser">
              <revision reference="../../../../../../../actions/hudson.plugins.git.util.BuildData/buildsByBranchName/entry/hudson.plugins.git.util.Build/marked"/>
            </buildChooser>
          </hudson.plugins.git.extensions.impl.BuildChooserSetting>
        </extensions>
      </scm>
      <node></node>
      <workspace>/home/user/ros2_ws/src/ros2_ci/jenkins_ci_project/jenkins/workspace/FastbotTests_main</workspace>
      <changelogFile>/home/user/ros2_ws/src/ros2_ci/jenkins_ci_project/jenkins/jobs/FastbotTests/branches/main/builds/4/changelog6969136610630246011.xml</changelogFile>
      <pollingBaseline class="hudson.scm.SCMRevisionState$None" reference="../../../actions/org.jenkinsci.plugins.workflow.steps.scm.MultiSCMRevisionState/revisionStates/entry/hudson.scm.SCMRevisionState_-None"/>
    </org.jenkinsci.plugins.workflow.job.WorkflowRun_-SCMCheckout>
  </checkouts>
</flow-build>